id: ICCC741D0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T23:19:24+00:00'
last_modified: '2022-06-10T05:15:42.476311+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC466
  title: 'བོད་བརྒྱུད་ནང་བསྟན་གྱིས་བོད་ཀྱི་སྲོལ་རྒྱུན་སྲིད་ཁྲིམས་གྱི་ངོ་བོ་དང་ད་སྔའི་གནས་སྟངས་ལ་ཤུགས་རྐྱེན་ཐེབས་པའི་སྐོར་ལ་ཅུང་ཙམ་དཔྱད་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B4BD:
      image_group_id: I2PD18735
      title: Volume 1 of bod brgyud nang bstan gyis bod kyi srol rgyun srid khrims
        gyi ngo bo dang da snga'i gnas stangs la shugs rkyen thebs pa'i skor la cung
        tsam dpyad pa/
      total_pages: 228
      order: 1
      base_file: B4BD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
